[package]
name = "facil"
version = "0.4.0"
edition = "2024"
rust-version = "1.88"
description = "A single-binary, TOML-driven tmux session templating and session manager"
license = "MIT"
repository = "https://github.com/doprz/facil"
homepage = "https://github.com/doprz/facil"
readme = "README.md"
authors = ["doprz"]
keywords = ["tmux", "cli", "tmuxinator", "session-manager", "toml"]
categories = ["command-line-utilities", "development-tools"]
exclude = ["*.nix", "flake.lock", ".editorconfig", ".envrc"]

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.4"
thiserror = "2"
clap_complete = { version = "4.6.9", features = ["unstable-dynamic"] }
serde_yaml_ng = "0.10.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"
