use std::collections::HashMap;
use std::path::Path;

use crate::config::model::{Pane, Project, Window, contract_home};
use crate::error::Error;
use crate::tmux::Tmux;

/// Inspect a live session and build the `Project` a `facil.toml` for it would need,
/// capturing layout and working directories only - commands, pre/post, and
/// tmux_options can't be recovered from live tmux state.
pub fn capture(tmux: &Tmux, session: &str, socket_name: Option<String>) -> Result<Project, Error> {
    let windows = tmux.list_windows(session)?;

    let mut pane_paths_by_window: Vec<Vec<String>> = Vec::with_capacity(windows.len());
    let mut all_paths: Vec<String> = Vec::new();
    for window in &windows {
        let target = format!("{session}:{}", window.name);
        let paths = tmux.list_panes(&target)?;
        all_paths.extend(paths.iter().cloned());
        pane_paths_by_window.push(paths);
    }

    let root = most_common(&all_paths);

    let project_windows = windows
        .into_iter()
        .zip(pane_paths_by_window)
        .map(|(window, paths)| Window {
            name: window.name,
            layout: Some(window.layout),
            pre_window: vec![],
            panes: paths
                .into_iter()
                .map(|path| Pane {
                    commands: vec![],
                    root: if Some(&path) == root.as_ref() { None } else { Some(contract_home(Path::new(&path))) },
                })
                .collect(),
        })
        .collect();

    Ok(Project {
        name: session.to_string(),
        root: root.map(|p| contract_home(Path::new(&p))),
        pre: vec![],
        post: vec![],
        tmux_options: None,
        socket_name,
        windows: project_windows,
    })
}

/// The most frequent path in `paths`, ties broken by first-seen order. `None` if empty.
fn most_common(paths: &[String]) -> Option<String> {
    let mut counts: HashMap<&str, usize> = HashMap::new();
    let mut order: Vec<&str> = Vec::new();
    for path in paths {
        let count = counts.entry(path.as_str()).or_insert_with(|| {
            order.push(path.as_str());
            0
        });
        *count += 1;
    }

    // Iterate in first-seen order and only replace on a strictly higher count,
    // so an earlier path wins any tie rather than `Iterator::max_by_key`'s
    // last-element-wins behavior.
    let mut best: Option<(&str, usize)> = None;
    for path in order {
        let count = counts[path];
        if best.is_none_or(|(_, best_count)| count > best_count) {
            best = Some((path, count));
        }
    }
    best.map(|(path, _)| path.to_string())
}

pub const HEADER_COMMENT: &str =
    "# generated by `facil snapshot` - layout and working directories only\n# (pre, post, tmux_options, and pane commands are not captured; review before use)\n\n";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn most_common_picks_majority() {
        let paths = vec!["/a".to_string(), "/b".to_string(), "/a".to_string()];
        assert_eq!(most_common(&paths), Some("/a".to_string()));
    }

    #[test]
    fn most_common_breaks_ties_by_first_seen() {
        let paths = vec!["/b".to_string(), "/a".to_string()];
        assert_eq!(most_common(&paths), Some("/b".to_string()));
    }

    #[test]
    fn most_common_empty_is_none() {
        assert_eq!(most_common(&[]), None);
    }
}
